-- MySQL Script generated by MySQL Workbench
-- Mon Sep 30 15:06:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MediSistema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MediSistema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MediSistema` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `MediSistema` ;

-- -----------------------------------------------------
-- Table `MediSistema`.`tipo_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediSistema`.`tipo_medico` (
  `id_tipo_medico` INT NOT NULL,
  `tipo_medico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_medico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediSistema`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediSistema`.`medicos` (
  `id_medico` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `tipo_medico_id_tipo_medico` INT NOT NULL,
  PRIMARY KEY (`id_medico`, `tipo_medico_id_tipo_medico`),
  INDEX `fk_medicos_tipo_medico_idx` (`tipo_medico_id_tipo_medico` ASC) VISIBLE,
  CONSTRAINT `fk_medicos_tipo_medico`
    FOREIGN KEY (`tipo_medico_id_tipo_medico`)
    REFERENCES `MediSistema`.`tipo_medico` (`id_tipo_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediSistema`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediSistema`.`pacientes` (
  `id_paciente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediSistema`.`internos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediSistema`.`internos` (
  `id_interno` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_interno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediSistema`.`tipo_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediSistema`.`tipo_empleado` (
  `id_tipo_empleado` INT NOT NULL,
  `tipo_empleado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediSistema`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediSistema`.`empleados` (
  `id_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo_empleado_id_tipo_empleado` INT NOT NULL,
  PRIMARY KEY (`id_empleado`, `tipo_empleado_id_tipo_empleado`),
  INDEX `fk_empleados_tipo_empleado1_idx` (`tipo_empleado_id_tipo_empleado` ASC) VISIBLE,
  CONSTRAINT `fk_empleados_tipo_empleado1`
    FOREIGN KEY (`tipo_empleado_id_tipo_empleado`)
    REFERENCES `MediSistema`.`tipo_empleado` (`id_tipo_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediSistema`.`vacaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediSistema`.`vacaciones` (
  `id_vacaciones` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `empleados_id_empleado` INT NOT NULL,
  `internos_id_interno` INT NOT NULL,
  `medicos_id_medico` INT NOT NULL,
  `medicos_tipo_medico_id_tipo_medico` INT NOT NULL,
  PRIMARY KEY (`id_vacaciones`, `empleados_id_empleado`, `internos_id_interno`, `medicos_id_medico`, `medicos_tipo_medico_id_tipo_medico`),
  INDEX `fk_vacaciones_empleados1_idx` (`empleados_id_empleado` ASC) VISIBLE,
  INDEX `fk_vacaciones_internos1_idx` (`internos_id_interno` ASC) VISIBLE,
  INDEX `fk_vacaciones_medicos1_idx` (`medicos_id_medico` ASC, `medicos_tipo_medico_id_tipo_medico` ASC) VISIBLE,
  CONSTRAINT `fk_vacaciones_empleados1`
    FOREIGN KEY (`empleados_id_empleado`)
    REFERENCES `MediSistema`.`empleados` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacaciones_internos1`
    FOREIGN KEY (`internos_id_interno`)
    REFERENCES `MediSistema`.`internos` (`id_interno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vacaciones_medicos1`
    FOREIGN KEY (`medicos_id_medico` , `medicos_tipo_medico_id_tipo_medico`)
    REFERENCES `MediSistema`.`medicos` (`id_medico` , `tipo_medico_id_tipo_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediSistema`.`consultas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediSistema`.`consultas` (
  `id_consulta` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `estado_consulta` VARCHAR(45) NOT NULL,
  `pacientes_id_paciente` INT NOT NULL,
  `medicos_id_medico` INT NOT NULL,
  `medicos_tipo_medico_id_tipo_medico` INT NOT NULL,
  PRIMARY KEY (`id_consulta`, `pacientes_id_paciente`, `medicos_id_medico`, `medicos_tipo_medico_id_tipo_medico`),
  INDEX `fk_consultas_pacientes1_idx` (`pacientes_id_paciente` ASC) VISIBLE,
  INDEX `fk_consultas_medicos1_idx` (`medicos_id_medico` ASC, `medicos_tipo_medico_id_tipo_medico` ASC) VISIBLE,
  CONSTRAINT `fk_consultas_pacientes1`
    FOREIGN KEY (`pacientes_id_paciente`)
    REFERENCES `MediSistema`.`pacientes` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_medicos1`
    FOREIGN KEY (`medicos_id_medico` , `medicos_tipo_medico_id_tipo_medico`)
    REFERENCES `MediSistema`.`medicos` (`id_medico` , `tipo_medico_id_tipo_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MediSistema`.`sustitutos_medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediSistema`.`sustitutos_medicos` (
  `id_sustituto_medico` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `medicos_id_medico` INT NOT NULL,
  `medicos_tipo_medico_id_tipo_medico` INT NOT NULL,
  PRIMARY KEY (`id_sustituto_medico`, `medicos_id_medico`, `medicos_tipo_medico_id_tipo_medico`),
  INDEX `fk_sustitutos_medicos_medicos1_idx` (`medicos_id_medico` ASC, `medicos_tipo_medico_id_tipo_medico` ASC) VISIBLE,
  CONSTRAINT `fk_sustitutos_medicos_medicos1`
    FOREIGN KEY (`medicos_id_medico` , `medicos_tipo_medico_id_tipo_medico`)
    REFERENCES `MediSistema`.`medicos` (`id_medico` , `tipo_medico_id_tipo_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `MediSistema` ;

-- -----------------------------------------------------
-- Placeholder table for view `MediSistema`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MediSistema`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `MediSistema`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MediSistema`.`view1`;
USE `MediSistema`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

